### ISSUE TITLE
An error occurred while installing iso4217parse==0.3!

### ISSUE THREAD

**Issue by IvanSGurdian** [tammoippen/iso4217parse#1]
Error when installing dependencies through Pipenv.
I'm using Python 3.7 and Pipenv for a Django Project.

Error occurs just when I try to run Pipenv Install to install al dependecies.

Working on Windows 10

**Comment by tammoippen** [comment]
This is an encoding issue by Windows (which by default assumes encoding cp1252). I will prepare a new release.

**Comment by tammoippen** [comment]
[0.4 is released](https://pypi.org/project/iso4217parse/0.4/). Installation on windows is good now. But similar issues persist with loading the data.

**Comment by tammoippen** [comment]
[v0.4.1](https://pypi.org/project/iso4217parse/0.4.1/) is good for windows use.

**Comment by IvanSGurdian** [comment]
Thank you!! I will re-add the dependency
