### ISSUE TITLE
Installation without data files

### ISSUE THREAD

**Issue by michaelconan** [tammoippen/iso4217parse#14]
Our team has been using this package for projects over the last 3-4 months.

In the last month, with the same package version, the package has been installing without the data files (`data.json` and `symbols.json`). We are able to import them into the virtual environment site-packages manually and get the code to run as a workaround.

**Version**: 0.6.0
**Environment**: VSCode development container (base Docker image `python:3.12-slim`) on WSL2, poetry environment manager

It is not clear whether this is an issue with the package itself or an unrelated issue that happens to only impact this package.

**Comment by tammoippen** [comment]
Hi @michaelconan ,

Both `data.json` and `symbols.json` are available in v0.6.0 - just unzip the [distributed package on pypi](https://files.pythonhosted.org/packages/78/28/49f0e3b073d1d53b5f0a1139ac90bb2794e1081c1fe99a0ce8681fff7454/iso4217parse-0.6.0.tar.gz).

I experimented with `python:3.12-slim`: 

- installing from pypi gave me an issue, that 0.6.0 is not available and it reverted to 0.5.1
- in the 0.6.0 version i fixed the [`pkg_resources` deprecation](https://setuptools.pypa.io/en/latest/pkg_resources.html) issue and use `importlib.resources`. Hence, calling `import iso4217parse` in python:3.12-slim with 0.5.1 crashed with an error that `pkg_resources` is not available.
- installing v0.6.0 directly from a .tar.gz gives an error, that i am installing version 0.0.0 => something in the build process is wrong

in #15 i think i fixed the issue, please try to install that version.

**Comment by michaelconan** [comment]
@tammoippen thanks a million for the quick response, we will test this today with 0.6.1 and report back with our results.

**Comment by michaelconan** [comment]
@tammoippen we tested the new version today and everything seems to be working properly now with the data files and importlib issues. Thanks again!
